name: Terraform Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    env:
        APPLICATION_CLIENT_ID: ${{ secrets.APPLICATION_CLIENT_ID  }}  
        DIRECTORY_TENANT_ID: ${{ secrets.DIRECTORY_TENANT_ID  }} 
        SECERET_ID: ${{  secrets.SECERET_ID  }}
        SUBSCRIPTION_ID: ${{  secrets.SUBSCRIPTION_ID  }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Azure Login
      run: |
        az login --service-principal -u ${{ secrets.APPLICATION_CLIENT_ID }} -p ${{ secrets.SECERET_ID }} --tenant ${{ secrets.DIRECTORY_TENANT_ID }}  

    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
